var hilangkanCard;(function(){'use strict';var canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d'),W=canvas.width=window.innerWidth,H=canvas.height=window.innerHeight,maxP=700,minP=1000,fireworks=[],timerId;window.addEventListener('resize',function(){W=canvas.width=window.innerWidth;H=canvas.height=window.innerHeight});function tick(){var newFireworks=[];ctx.clearRect(0,0,W,H);fireworks.forEach(function(firework){firework.draw();if(!firework.done)newFireworks.push(firework);});fireworks=newFireworks;window.requestAnimationFrame(tick)}
function Vector(x,y){this.x=x;this.y=y}
Vector.prototype={constructor:Vector,add:function(vector){this.x+=vector.x;this.y+=vector.y},diff:function(vector){var target=this.copy();return Math.sqrt((target.x-=vector.x)*target.x+(target.y-=vector.y)*target.y)},copy:function(){return new Vector(this.x,this.y)}};var colors=[['rgba(179,255,129,','rgba(0,255,0,'],['rgba(0,0,255,','rgba(100,217,255,'],['rgba(255,0,0,','rgba(255,255,0,'],['rgba(145,0,213,','rgba(251,144,204,']];function Firework(start,target,speed,isSpecial){this.start=start;this.pos=this.start.copy();this.target=target;this.isSpecial=isSpecial;this.spread=isSpecial?3000:Math.round(Math.random()*(maxP-minP))+minP;this.distance=target.diff(start);if(isSpecial){this.speed=12}else{this.speed=speed||Math.random()*6+2}
this.angle=Math.atan2(target.y-start.y,target.x-start.x);this.velocity=new Vector(Math.cos(this.angle)*this.speed,Math.sin(this.angle)*this.speed);this.particals=[];this.prevPositions=[];var colorSet=colors[Math.round(Math.random()*(colors.length-1))];for(var i=0;i<this.spread;i++){this.particals.push(new Partical(target.copy(),colorSet,isSpecial))}}
Firework.prototype={constructor:Firework,draw:function(){var last=this.prevPositions[this.prevPositions.length-1]||this.pos;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(this.pos.x,this.pos.y);ctx.strokeStyle='rgba(255,255,255,.7)';ctx.stroke();this.update()},update:function(){if(this.start.diff(this.pos)>=this.distance){var newParticals=[];this.particals.forEach(function(partical){partical.draw();if(!partical.done)newParticals.push(partical);});this.particals=newParticals;this.prevPositions=[];if(this.isSpecial&&!this.hasTriggeredResume){this.hasTriggeredResume=!0;var textElement=document.getElementById('nameText');textElement.classList.add('muncul');for(var i=0;i<20;i++){setTimeout(function(){addFirework()},Math.random()*1000)}
setTimeout(randomFirework,3000)}
if(!newParticals.length)this.done=!0}else{this.prevPositions.push(this.pos.copy());if(this.prevPositions.length>8){this.prevPositions.shift()}
this.pos.add(this.velocity)}}};function Partical(pos,colors,isSpecial){this.pos=pos;if(isSpecial){this.ease=0.015;this.speed=Math.random()*8+4;this.gravity=0.03;this.decay=0.003}else{this.ease=0.2;this.speed=Math.random()*6+2;this.gravity=Math.random()*3+0.1;this.decay=0.01}
this.alpha=.8;this.angle=Math.random()*(Math.PI*2);this.color=colors[Math.round(Math.random()*(colors.length-1))];this.prevPositions=[]}
Partical.prototype={constructor:Partical,draw:function(){var last=this.prevPositions[this.prevPositions.length-1]||this.pos;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(this.pos.x,this.pos.y);ctx.strokeStyle=this.color+this.alpha+')';ctx.stroke();this.update()},update:function(){if(this.alpha<=0){this.done=!0}else{this.prevPositions.push(this.pos.copy());if(this.prevPositions.length>10)this.prevPositions.shift();if(this.speed>1)this.speed-=this.ease;this.alpha-=this.decay;this.gravity+=0.01;this.pos.add({x:Math.cos(this.angle)*this.speed,y:Math.sin(this.angle)*this.speed+this.gravity})}}};function addFirework(target,isSpecial){var startPos=new Vector(W/2,H);target=target||new Vector(Math.random()*W,Math.random()*(H-300));fireworks.push(new Firework(startPos,target,undefined,isSpecial))}
canvas.addEventListener('click',function(e){addFirework(new Vector(e.clientX,e.clientY))},!1);function randomFirework(){addFirework();timerId=window.setTimeout(randomFirework,Math.random()*500)}
hilangkanCard=function(){clearTimeout(timerId);var card=document.getElementById('mainCard');var container=document.getElementById('cardContainer');card.classList.add('keluar');setTimeout(function(){container.style.display='none';addFirework(new Vector(W/2,H/3),!0)},1500)}
tick();randomFirework()})()
